### ISSUE TITLE
Rename access_token to password in config.yml

### ISSUE THREAD

**Issue by cshold** [Shopify/themekit#104]
Common issue when getting setup for the first time is for the dev to use Shopify-generated API key instead of the password from their private app page. Any other possible fixes?

cc @stevebosworth @t-kelly @AWaselnuk

**Comment by AWaselnuk** [comment]
Could be as simple as including a comment in config-sample.yml if you want to stay consistent with theme kit args.

**Comment by csaunders** [comment]
We go back to using "password"?

The private apps page should really be updated in my opinion. For private apps the API Key isn't actually used for anything.

/cc @jamesmacaulay

**Comment by stevebosworth** [comment]
I'm cool with going back to `password`.  Most are used to that from the bad old theme gem days

**Comment by zachharkey** [comment]
At the very least, it would be nice to update the [docs](http://themekit.cat/docs/) to make it clear that "access_token" means Password, not API Key.

**Comment by schaeken** [comment]
Ran into this issue yesterday. There is no access_token on the private app page 

![https://screenshot.click/12-46-6ip0d-104qj.jpg](https://screenshot.click/12-46-6ip0d-104qj.jpg)

Something needs to change somewhere, instead of hitting a wall and not knowing what went wrong.

**Comment by stevebosworth** [comment]
Can we accept either `password` or `access_token` so this isn't a breaking change?

**Comment by playmakers** [comment]
:+1:  for updating docs, just to mention `'access_token' is NOT API Key` would have helped me a lot...

**Comment by chrisbutcher** [comment]
As a first step, I'm going to switch the font-family specified in the docs, since the one used (Muli) won't exist for most users, and the fallback sans-serif font don't seem to display <strong> tags properly. The docs will now look like this:
![image](https://cloud.githubusercontent.com/assets/1916444/13269504/0562030a-da56-11e5-8c7a-506cf63d3cca.png)

As for adding a comment to config-sample.yml, I think that's a good idea, too.

**Comment by chrisbutcher** [comment]
Fixed in 0.3.6
