### ISSUE TITLE
Timber can't be retrieved from github

### ISSUE THREAD

**Issue by anaralvarado** [Shopify/themekit#119]
theme bootstrap -setid=true -prefix="brand"

returns 

'https://github.com/Shopify/Timber/archive/v2.1.4.zip' cannot be retrieved from Github

**Comment by ilikeorangutans** [comment]
@anaralvarado I'm unable to reproduce this. What version of themekit are you using? And, is this issue still happening for you?

**Comment by anaralvarado** [comment]
Yes, it's still happening. I'm on Theme Kit v0.3.4 ... Searched for a removal method to reinstall but didn't find any documentation on it.

**Comment by ilikeorangutans** [comment]
@anaralvarado Did you set up a new configuration file with a valid access token? I've been able to get the same error when not setting an access token.

**Comment by anaralvarado** [comment]
Finally got it to work. It was the config file. Thank you!

**Comment by jamieowen** [comment]
I had similar issues..

It wasn't immediately obvious what was the problem. Some descriptive error messages would be handy on this tool.. Saves people bashing their heads ;)

I had different issues depending on permission settings in the Private App ( the passwords in config.yml were fine. )

Just having read access allowed for 'theme download' commands. But running 'theme bootstrap' failed. ( showing only the cannot download zip error mentioned above )
Turns out you need the "Theme templates and theme assets" read/write access in Private App settings for "theme bootstrap" to work.

Also 'theme upload' commands with read access only gives errors like : "Cannot remove files that would make a theme invalid." rather than: "check yo' god damn read/write permissions brother!"

All a bit cryptic..
