### ISSUE TITLE
error message 429 - too many requests with `replace`

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/themekit#136]
When running `theme replace` for themes that have many files, it's common to see a 429 error that says something like:

```
[429]Could not perform Update to templates/page.glow.liquid at *.myshopify.com
	json: cannot unmarshal string into Go value of type themekit.AssetError
```

A couple things:

1. The error message occurs when there are too many requests.  I think it would be beneficial if the error message said that instead of the "cannot unmarshal string into Go" message.

  > 429 Too Many Requests (RFC 6585)
The user has sent too many requests in a given amount of time. Intended for use with rate limiting schemes.
  > source: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

2. Would it be possible to introduce some sort of fix that either makes Theme Kit wait a set amount of time when a limit has been reached?  

3. Could there be a summary message at the end of `theme replace` and `theme update` that tells you if files were skipped and prompt you to run the command again?

### Screenshot

I have included a screenshot of a time I received an error.  In this case I was replacing a theme that has 200+ files with a theme that has ~60 files.

![http://take.ms/rRJs9](http://take.ms/rRJs9)

In this case it "timed" out after 93 actions (update, remove).  In the past we've seen it time out after ~115 actions.

**Comment by NathanPJF** [comment]
May be similar to #74 

cc @ilikeorangutans @chrisbutcher

**Comment by ilikeorangutans** [comment]
@NathanPJF these are actually really good suggestions! I will look into that later this week!

**Comment by cshold** [comment]
I hadn't had this error in a while until this morning where it seems intermittent. Bumping it to see if we can get this looked at again

**Comment by tanema** [comment]
I am seeing a lot of github traffic to this issue lately. If you are having this issue still please comment on this issue because I am(was) pretty certain that I solved this issue and I would love to know if I need to re-address it.

**Comment by benVigie** [comment]
Hi @tanema , I'm experiencing this issue this morning, but it's due to my use of your tool. I'm posting the solution here in case it can help others with the same problem.

First thing first, I have `ThemeKit 0.6.12` on a Mac, several terminals open with a `$ theme watch` running all the time in one of them.

So on my side, I can **push my updates** with `$ theme upload` without any problem. But I have the `429 - too many requests` **when I want to pull theme update** with a `$ theme download`. Both actions are performed on my Shopify `development` env.  Another thing relevant it that I always getting the error when I retrieve the 42th asset each time.

I noticed that both commands `watch` and `download` are performing request at the same time ! Indeed, a file refresh from `download` triggers a push from `watch` ...
**If I close** `$ theme watch` **before running** `$ theme download`, **everything's fine** and I'm able to fully download without any issue.

What I can't understand is why `watch` will perform a push **if the updated file is the exact same one as the local one** ? Don't you guys check this ?

Hope it helps !

**Comment by tanema** [comment]
@benVigie This is because themekit was never designed to be used this way. I cannot reasonable throttle api usage across multiple running instances of themekit. Of course `download` and `watch` are performing actions at the same time. `watch` is designed to watch for file changes and `download` changes all the files. Why would I check if the file is different on a file that has just emitted a change event?

And when you say 

>What I can't understand is why watch will perform a push if the updated file is the exact same one as the local one ? Don't you guys check this ?

What are the two files I can compare there? The file that was just change by the download command IS the "local one".

**Comment by benVigie** [comment]
> This is because themekit was never designed to be used this way

OK, so it seems I had a bad vision / use of your tool. As a fullstack dev, I always have several terminals open with my watchers while I'm using git on other ones to perform my push/pull on repos. I can't use the same dynamic setup with your tool, understood it now.

The solution I proposed wasn't to to throttle the API even more or to update the `watch` command, sorry if I wasn't clear. A proper implementation would be to perform check on the `download` command.

The idea would be to compare a list of local file hashes with a remote one. If files are different, download the new version. If not, save bandwidth !

Several advantages for everyone:

- reduce amount of requests
- save bandwidth
- reduce the download time for the developer
- ... and I will be able to keep my watchers on while I download other guys stuff 😄

**Comment by tanema** [comment]
@benVigie Then you can look forward to version 0.7.x which will have checksum checking. However I cannot guarantee that this will fix your issues since there may be race conditions checking the manifest since there is no reasonable way to maintain state/mutexes/rate limiting across command instances. Also up until now (the 7 series release) we have not had considerable motivation to introduce another file into theme development workflow. We are well aware the advantages and all of these things have been considered and decided upon. Please be aware of your tone on this repo, and be aware that you are literally telling us how to do our job by saying `A proper implementation would be to ....`

**Comment by benVigie** [comment]
Oh no, sorry, it wasn't my intention at all !!! English is not my native language, I feel sorry if you took my comments as "aggressive" ! My only goal was to help you guys on improving this tool, but it seems you're on good way with version 0.7.x regarding your comment.

I will definitely take a look on it just for the download speed improvement it will definitely be a plus for me!

**Comment by tanema** [comment]
@benVigie  No worries, it happens. `0.7.0` had to be rolled back last week however 0.7.1 will be release next week and you will be able to update then.

**Comment by benVigie** [comment]
Good to heard, looking forward to it 😃  !
Thanks for the note @tanema and sorry again if I sound offensive.
