### ISSUE TITLE
Long files being cut off on upload

### ISSUE THREAD

**Issue by AlfalfaAnne** [Shopify/themekit#200]
I'm having the same issue as #99  with long files (both JS and CSS).

Details:
- no errors from Terminal and the "Successfully performed Update operation for file" is returned
- long file is cut off at random (usually 4000 line mark)
- if I stop the current theme watch and rerun, it generally works, but only the first time
- only happens with extremely long files and if I shorten them, it's all good
- never had this issue with the theme gem - it's only come up since I swapped to Theme Kit

Running:
Sierra 10.12
Theme Kit v0.4.3

**Comment by tanema** [comment]
Hey @AlfalfaAnne I will look into this. Since there was a previous PR that fixed this, it may just be a regression so I will look into just applying the fixes again. Cheers.

**Comment by tanema** [comment]
@AlfalfaAnne do you have a file you can share with me at all to try and reproduce this? The code that fixed this issue is still in place and there should be no file limit so I will have to try and reproduce it locally.

**Comment by AlfalfaAnne** [comment]
@tanema For sure - can I just send the file to timanema@gmail.com ?

**Comment by tanema** [comment]
Since this is for work you can send it to tim.anema@shopify.com

**Comment by tanema** [comment]
Hey @AlfalfaAnne just a quick question, what text editor are you using? I can reproduce it in vim and I see several notifications from fsnotify part way through writing the file because apparently my vim is not setup for atomic writes. So this means that the first few events are partially written files. And since we throttle these events we only get the first event with the partially written file.

I started up atom (for the first time ever) and I saved your styles.css file and it worked the first time around.

I will have to figure out how to fix this because you shouldn't have to change your env to use our tool but if you can confirm your editor that would be helpful.

**Comment by AlfalfaAnne** [comment]
Hey @tanema ,

I'm using Sublime Text 3, but I'll happily try Atom for today if that helps me work faster. I'm currently working on a 1000 line JS file and I'm having to `theme upload assets/app.js.liquid` each time in order for it to not be cut off. :/ That command works every time though (unlike `theme watch`)

Not helping out my situation, I noticed my upload speed is crazy slow today.

**Comment by tanema** [comment]
Yeah `upload` would always work because the file isn't partially written when it is sent to the server. I will try and come up with a solution to this soon. Thank you for your patience.
