### ISSUE TITLE
[403]Insufficient permissions to perform Remove to layout/theme.liquid

### ISSUE THREAD

**Issue by plisvb** [Shopify/themekit#233]
Getting this error in terminal when I save a file for updating.  If I save again, it works fine.  Any idea why?

**Comment by tanema** [comment]
What editor are you using and is it a large file? Some editors create a swap file of the changes, delete the current file then put the swap file in place. I am debouncing all the events but it seems like the remove is the most recent event it catches rather than the write. I will play will the debounce time for this.

**Comment by plisvb** [comment]
Hi Tanema,

Using coda on the mac. it's my theme.liquid file which is 16kbs but it has issues with all files.  I save the file, it removes, I save the file again, it works fine.  Assets images etc... work perfectly
