### ISSUE TITLE
Ability to use json OR yaml for config file

### ISSUE THREAD

**Issue by stevebosworth** [Shopify/themekit#263]
Most of our tooling is done in node and Shipit uses ejson so our other tools are converting `.yml` files to `.json`. It would be great to be able to pass Themekit a json file instead of a yml file if we want.

**Comment by justinmetros** [comment]
If anyone has moved to json ( love this feature, thank you! ), and gets this error on theme watch:
`Error: json: cannot unmarshal string into Go value of type time.Duration`

In your config.json, make sure time is a number, not a string, with no "s" at the end. e.g. 
`"timeout": 30,`
not
`"timeout": "30s",` or `"timeout": 30s,`

Here is a sample config.json that watches a folder called "theme", since this hasn't made it into the docs yet:
` 
{
  "development": {
    "password": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "theme_id": "123456789",
    "store": "myshop.myshopify.com",
    "directory": "theme/",
    "bucket_size": 40,
    "refill_rate": 2,
    "timeout": 10,
    "ignores": [
      ".DS_Store",
      "Thumbs.db",
      ".Trashes"
    ] 
  }
}
`

**Comment by justinmetros** [comment]
There seems to be a bug with timeout using the json format. 

If you convert YAML to json, the 30s turns into a string `"timeout": "30s"`, that throws an error`json: cannot unmarshal string into Go value of type time.Duration`

If you create it as a number, and drop the "s", `"timeout": 30,` you get an error `Put https://xxxxxx.myshopify.com/admin/themes/1234566789/assets.json: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)` unless you set timeout to something like at least `"timeout": 1000000000,`

Any insight into what time units are being used there? 

The default timeout value is fine for most cases but I need to up for themes with larger assets.

**Comment by tanema** [comment]
I have left the json config undocumented because it is not the recommended config usage. The issue with your timeout however is that the value when given to a Go `time.Duration` in the form of an int is used as a nanosecond so your value of `1000000000` nanoseconds is one second.

**Comment by justinmetros** [comment]
Ah, that makes sense! Thanks for the insanely quick response!

The config.json file is very nice for us compared to config.yml because it's really easy to natively pass some of the store data to Gulp, BrowserSync, etc without having to add an extra dev dependency to get at the info, or have it duplicated in another place. That said YAML does have its benefits over json, so I am happy having the undocumented option. Everything is working well so far except for getting the time units wrong ;)

Once again, appreciate all the efforts. ThemeKit rocks!
