### ISSUE TITLE
[Docs] Clarification on using "Environment Variables"

### ISSUE THREAD

**Issue by CurtisL** [Shopify/themekit#342]
In trying to keep passwords out of the config.yml file I came across the [Environment Variables](http://shopify.github.io/themekit/configuration/#environment-variables) section of the docs. but that doc doesn't really explain how/where those environment variables should be used.

A `.env` file doesn't appear to work so I'm assuming there must be something I'm missing. Is this a useable feature?

While digging for an answer I saw #161 mention this as an enhancement and was closed during a merge, but that shed no additional light on this as to how it was actually implemented.

**Comment by justinmetros** [comment]
Environment Variables are specific to your machine and they live in the settings/config of whatever shell you are using. If you are on OSX, your shell may be bash or zsh, or whatever. bash is default on OSX, not sure about Windows or other OS's.

Every machine is setup differently, but if you know your shell, Google up how to set up environment variables in it. A quick search gave me this, seems like a decent link: https://codewithintent.com/how-to-setup-os-x-el-capitan-environment-variables-create-read-update-delete/

For what it's worth, I keep my config.json ( I use the undocumented .json config file instead of .yml, I prefer it, so shoot me ;) and add it to my .gitignore file. This way i can see the settings easy right in my editor ( quickly add new theme_id's, etc ) and I know that file is not leaving my machine unless I manually give it to someone. We use private repo's for all client work, so in the README.md file, instructions are included for any future devs to create their own config file if they have access the site's applications.

Hope that helps :)

**Comment by tanema** [comment]
Hey @CurtisL You're right I should add a bit of clarification on how to set your environment variables. I think @justinmetros explain it pretty well. If you are using a OSX/linux shell you can just run `export THEMEKIT_PASSWORD=mypassword` and that will set your environment variable. You can then put that line in your .bashrc and have that run whenever you start your shell.

@justinmetros Thanks for the help but here is a sweet tip. The only reason json is supported in this tool is for ejson purposes so that we could commit the ejson file to a repo for automatic testing.
