### ISSUE TITLE
Version 1 interface.

### ISSUE THREAD

**Issue by tanema** [Shopify/themekit#344]
The interface for themekit isn't the best and is ambiguous in some commands. We should make it better.

Design Doc:

https://docs.google.com/document/d/1QvkJP_2rnpVxcz5Lwqi6hPWnSsuEet-ngcxAfv-7eSw/edit?usp=sharing

**Comment by cameronroe** [comment]
Just took a look. I think `sync` is a good idea and it should definitely integrate with browsersync to `--watch` files on change with browser refreshing.

I would also check out the [Firebase CLI](https://github.com/firebase/firebase-tools) as it has a lot of great conventions (google) which would be good to model.

**Comment by tanema** [comment]
browser sync is out of the scope of themekit and will be part of other tools that will soon be open sourced.

**Comment by chryton** [comment]
Would `theme customize` be something reasonable? Especially with the advent of sections it might be helpful to be able to pull up the theme customizer to be able to see and edit those sections.

I'd be willing to contribute this part of functionality.

**Comment by tanema** [comment]
@chryton I am not sure I fully understand. Would you just like a shortcut to opening the online store editor?

**Comment by chryton** [comment]
Correct, just like what `theme open` does.

**Comment by tanema** [comment]
Yeah that wouldn't be too hard.

**Comment by cameroncowden** [comment]
Would it be possible to allow us to set the target browser to use for theme open? I use Chrome as my default browser, but it's heavily loaded with extensions, so when I'm developing I use Chrome Canary. Not a big deal since all I have to do it snag the url while chrome is loading the page (while it still contains url param for preview theme), and drop that into canary, but it would be more convenient if I could define the browser either as a flag e.g. `theme open --canary `or by adding a line to config.yml, perhaps pointing to the canary executable. This would also be convenient for cross browser testing.

**Comment by tanema** [comment]
@cameroncowden please open a new issue for this as it has no relation to version 1 planning.

**Comment by kj** [comment]
I had planned to implement a little wrapper around Theme Kit to automate my team's workflow, but when I came to duplicating an existing theme (as we manually would in the Shopify admin) I found nothing in the Shopify API that allows that. The create endpoint only seems to take a URL to a .zip file. So I'm wondering if you had any plans on how to implement theme duplication efficiently, seeing as it's under consideration here?

Ideally the Shopify API would allow a theme ID or some kind of magic '/admin/themes/123456789.zip' path to be passed to the 'src' field when creating a new theme.

**Comment by kj** [comment]
@tanema To further clarify what I mean:

https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/duplicate-theme-via-api-494136

While this can theoretically be done by copying assets one by one, for larger themes that will take a significant amount of time due to the API call limit. Shopify has obviously already implemented the duplication internally, and if that were exposed via the API it could turn minutes and hundreds of requests into a single request and a matter of seconds.
