### ISSUE TITLE
Changing git branches while `theme watch` resets settings content in store

### ISSUE THREAD

**Issue by Liopia** [Shopify/themekit#361]
While working with another developer on a theme (Timber framework based) we found that if we kept `theme watch` running while changing branches (between a dev branch and master) the branch change caused a slew of files to upload and any previously added Section Block data or General Settings to revert to their default value.

This happens even when the branches have no changed files between them.

Obvious solution is to turn off the theme kit watcher.
But it makes the data in a shop to be rather fragile to one of us forgetting.

Using: Shopify Theme Utilities 0.6.9

**Comment by tanema** [comment]
This should not be the case at all. This case was handled a while ago. This is what you should see if you are using an up to date version of themekit 
![image](https://cloud.githubusercontent.com/assets/463193/23660206/aabcbd4c-0316-11e7-91e1-bf71a953d447.png)

The only situation where this would not work is if you do not have your config checked in to your VCS. In this situation I cannot help you because themekit will not add code to handle only git specifically. It will work the exact same for all VCSs

**Comment by tanema** [comment]
Okay so I have I also found that if your config is the exact same on all of your branches you will get the behaviour that you described, because git won't touch it. I will see what I can do about this.

**Comment by tanema** [comment]
I just released `v0.6.10` that will handle git branch changing
