### ISSUE TITLE
Watching file changed inside a docker container

### ISSUE THREAD

**Issue by JasonShin** [Shopify/themekit#369]
Hi, I've set up a simple docker container for my theme development. Unfortunately ```theme watch``` wouldn't pick up file changes made from host machine. Is there any way to resolve this?

**Comment by tanema** [comment]
Sorry you will have to give me a whole bunch more information. Why did you setup a container for development. What is the setup? Do you have your files in the container and running themekit from host? If you are running themekit from the container how are you installing themekit in your container?

**Comment by tanema** [comment]
Any update?

**Comment by JasonShin** [comment]
Hi, sorry about late reply. I've lost my Dockerfile but it was quite simple. It was like
```
FROM ubuntu:latest

# aptget update, essential packages
# install node npm
# install linux version of themekit

```
And I've created docker-compose that builds this dockerfile and shares volume ``` # volume share . /home ```. And I've ran the docker image by giving a interactive mode flag ``` docker run -it themekit bash```

To be honest, I've tried out this setup as an experiment.

**Comment by JasonShin** [comment]
I haven't written in Go before but I've noticed it's using 'fsnotify' for watching file system change. I found this issue https://github.com/fsnotify/fsnotify/issues/152 but I guess that's not very helpful =(..  I wonder how Nodemon can achieve file watch across NFS using --legacy flag

**Comment by tanema** [comment]
That is a good find. I am going to close this since it seems like there is a limitation of the file watcher and really there is no reason to be doing theme development in a container. Your theme is deployed on shopify and you don't need any other services like databases/memstores.

**Comment by JasonShin** [comment]
agreed =)..

**Comment by krumware** [comment]
We are new to themekit, but use containers for most things. Here it would be useful, since we can use the container to encapsulate the themekit, and allow devs to work with the themes without knowing how to install/manage themekit.  (which does sound a bit silly, since they need to learn liquid anyways, but its one less thing to think about)

In legacy mode, nodemon uses polling to detect file changes.  This is also useful in some cases where there are a large number of files to watch.
I don't have much experience with golang, but this might serve as a useful reference: https://github.com/fsnotify/fsnotify/issues/9

**Comment by tanema** [comment]
@krumware I am still working a better installer for windows, would that alleviate this issue?
 Supporting a polling fallback just for container development adds significant complexity to themekit and supports a very small amount of user base.

**Comment by krumware** [comment]
I think that it would. Even a powershell script or using a package manager like Chocolatey would help.

I also agree that those using this method (while becoming more common) is still too small of a user group, and likely will be alleviated by enhancement to Docker on Windows in (hopefully) short time.

**Comment by JasonShin** [comment]
Well, I think it would still be useful to support file change events inside containers because in larger scale shopify theme development, it would be nicer to encapsulate your development environment inside containers  (e.g. it enables developers to work in consistent environment for package management systems like NPM).

**Comment by tanema** [comment]
@JasonShin If you are still interested in getting themekit to work in a Docker environment, I am in the process of moving the file watching over to a polling process to ensure that it works more uniformly on any operating system. You can give this a try by using v1.0.0-pre in your docker container. This can be done by installing themekit and then running `theme update --version=v1.0.0-pre`. I am not sure what is the best way to install themekit in a container because the install script requires python and curl (`curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python`)
