### ISSUE TITLE
Feature Request: Allow organizing with subdirectories

### ISSUE THREAD

**Issue by lastobelus** [Shopify/themekit#409]
One of my current clients has several hundred files in each of assets, layouts & snippets. It would be a large productivity boon if I was able to organize them in subfolders in git & textmate.

The simplest way would be for the uploaded name to be the path + name, replacing '/' with '-' (ex: `product/page/bundle-logo.liquid` gets uploaded as `product-page-bundle-logo-liquid`)

Downloading should not create any new directories, but use existing ones that match from left to right (ex: `product-page-bundle-logo.liquid` would go to `product/page/bundle-logo.liquid` if `product/page` subdir exists and `produc/page/bundle` doesn't)

Handling `templates/customers` would be a special case.

I'm not a Gogrammer, but I could probably provide a first cut at this if I was confident in it getting in.

**Comment by tanema** [comment]
This is an interesting idea. It has a lot of complexity in it.

- If I go with your example (`product-page-bundle-logo.liquid` => `product/page/bundle-logo.liquid`) how could I tell what to do with that file on a complete first download?
- If I do end up implementing this and users get used to it, I would get a lot of confusion and support debt from new users trying to use these files and not being able to use the file with a path `product/page/bundle-logo.liquid`
- A simpler problem is being able to opt-in/out and change the separator because if users already have files name `product-page-bundle-logo.liquid` and then they download, they get a whole bunch of new files that are not where they expect.

I like this idea because I like the amount of flexibility possible in it however I think that it might be hard to work into the codebase.

**Comment by keyurshah** [comment]
that's interesting, perhaps add a prefix to any generated file, `tk-` to namespace it as a themekit file

**Comment by illarionvk** [comment]
Shopify themes are quite complex even with the current shallow folder structure. I'd recommend cleaning up the theme assets instead of introducing yet another layer of complexity, 

The new ['image_picker' setting type](https://help.shopify.com/themes/development/theme-editor/settings-schema#image-picker) and [Sections](https://help.shopify.com/themes/development/theme-editor/sections) allowed us to slim down our clients' custom themes considerably.

**Comment by tanema** [comment]
@illarionvk Thank you for more context, as a tool developer I do not always have full context of the usages or full in depth theme development workflow so I really appreciate multiple oppinions.

**Comment by frehner** [comment]
@illarionvk do you keep track of code outside of shopify (e.g. local git repo that you push)? If so, I would love to hear how you handle Shopify Sections and merging changes between what's local and what's on the live site.

**Comment by illarionvk** [comment]
@frehner We track all theme changes in a Git repo (hosted on Bitbucket). We have [two environments](http://shopify.github.io/themekit/configuration/#config-file) in the ThemeKit config: `development` and `live`

My process:

1. Duplicate the live theme
1. Commit any changes to the git repo
1. Work on the duplicated theme using the default development environment
1. Commit my changes to the git repo
1. Download the live theme into my working copy using live environment 
    ```
    ./theme download --env live
    ```
1. Merge client's changes, if any. [Kaleidoscope](http://www.kaleidoscopeapp.com/) diff tool helps a lot with that.
1. Upload merged changes to my theme
1. Publish my theme

**Comment by tanema** [comment]
I have done some thinking about this and I really thing that this would cause more harm then good. The main being that the files on the online editor would be in different locations than on your local computer. This I think is harmful since themes have very strict structures and I would be breaking this with a change that hid this. I hope that @illarionvk tips could help your organize your theme into a more manageable form.
