### ISSUE TITLE
Error while setting up via curl on Mac OS X 10.6.8 Snow Leopard

### ISSUE THREAD

**Issue by ninjapanda** [Shopify/themekit#410]
```
$ curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
Password:
Fetching release data
Downloading version v0.6.12 of Shopify Themekit
Traceback (most recent call last):
  File "<stdin>", line 49, in <module>
  File "<stdin>", line 22, in install
  File "<stdin>", line 42, in __download
  File "<stdin>", line 33, in __findReleaseURL
  File "<stdin>", line 30, in __getArch
KeyError: 'darwin i386'
```

**Comment by tanema** [comment]
can you please paste the output of this in your command line? `echo "$(uname) $(uname -m)"`

What machine are you running as well because for some reason it has identified your machine as 32bit darwin which hasn't been around for a while. I can make the install script work without the architecture on OSX but I am very curios why your machine is identified as such.

**Comment by ninjapanda** [comment]
@tanema - sorry for the late reply.

`echo "$(uname) $(uname -m)" ` outputs **Darwin i386**

The maschine is a MacBook Pro "Core 2 Duo" 2.26 13" (SD/FW 800) Mid-2009.
