### ISSUE TITLE
Theme upload erases data

### ISSUE THREAD

**Issue by wiznia** [Shopify/themekit#412]
I make changes on my local shopify files, I have custom sections and snippets I already added to the theme editor and filled them in.

Once I commit everything, I do `theme upload` to upload all files to shopify.

After that, if I refresh the theme editor, all the custom content I added to any page gets deleted.

**Comment by tanema** [comment]
So you edited files on the online editor, then you uploaded changes from your machine and they got wiped out?

**Comment by tanema** [comment]
If that is the case this is because shopify's theme api does not handle partial uploads nor does it diff changes. There is no way to merge your changes in any sane way using a REST API. However please consult this issue for catching moments when uploading with change the file https://github.com/Shopify/themekit/issues/330

**Comment by utegard** [comment]
I have the exact same problem. I'm editing the theme files on my local machine. When I use "theme upload" all my custom content like sections and blocks are erased when I go to my site. Since my site is only sections and blocks my site gets blank directly after a deploy. Is there anything I can do to make everything be as it was except from the changes I've made locally? It's so frustrating to create all content again for 5+ pages everytime I make a deploy. #

**Comment by mbavio** [comment]
I have the same problem. I didn't change files on the online editor, I changed sections settings. They all wipe out every time I use theme upload. Is there any workaround for this?

**Comment by tanema** [comment]
Please note the answer already posted, please also see the work done on the open PR. Also if you are making changes to your theme on shopify then on your local machine, you should be downloading those changes because otherwise you will overwrite them. If you edit a word document in one folder and copy another word document over it do you expect that the word document now has both of the files contents?

**Comment by mbavio** [comment]
I'm not making changes to the theme, I'm making changes to the sections settings in the editor. How do you download those? Do you understand what I mean? You really think I don't know how to do simple version control? 🤣

**Comment by tanema** [comment]
Those changes are made to your theme. They are reflected in your config/settings_data.json

**Comment by mbavio** [comment]
And I didn't know that! 

@tanema Thanks, now I know how to keep data from getting lost on Shopify and how to edit a Word document, what a day!

**Comment by tanema** [comment]
You may also want to watch out for `config/settings_schema.json` A lot of theme developers just ignore most of the files in the config folder.
