### ISSUE TITLE
Ability to define target browser for theme open

### ISSUE THREAD

**Issue by cameroncowden** [Shopify/themekit#427]
Would it be possible to allow us to set the target browser to use for theme open? I use Chrome as my default browser, but it's heavily loaded with extensions, so when I'm developing I use Chrome Canary. Not a big deal since all I have to do it snag the url while chrome is loading the page (while it still contains url param for preview theme), and drop that into canary, but it would be more convenient if I could define the browser either as a flag e.g. theme open --canary or by adding a line to config.yml, perhaps pointing to the canary executable. This would also be convenient for cross browser testing.

**Comment by tanema** [comment]
I will look into the possibility of this however I am not sure how much I can do since it is just a system call to `open` in most cases which will delegate the opening to your operating system which is why it will open your default browser. Is there some reason why you would need this beyond opening the browser once? For instance are you making a tool to open it in many different browsers ect.?

**Comment by tanema** [comment]
@cameroncowden please review the PR description for limitations of this sort of functionality

**Comment by cameroncowden** [comment]
@tanema Ahh, gotcha. Like I said - not a big deal. 
Standard use-case would be opening firefox, ie, edge, and chrome on windows and safari, firefox, chrome more easily to verify cross-browser compatibility.
In terms of automation it could be beneficial, but I think it could easily be handled either upstream or downstream of themekit.
