### ISSUE TITLE
Upload theme to another store

### ISSUE THREAD

**Issue by hatsumatsu** [Shopify/themekit#445]
Not sure if this is the right channel for questions like this:

I developed a theme with themekit via `theme bootstrap`. I now want to deploy this theme to another store. I changed the API credential password and the store URL in `config.yml` but `theme upload` gives me 

````
Status: 404 Not Found
Errors: This file is not part of your theme.
````
for all files. What am I missing here?

Thanks!

**Comment by tanema** [comment]
This might mean that you have your theme id wrong. Sometimes the themes API errors can be a bit opaque.

**Comment by hatsumatsu** [comment]
I kept the existing theme ID. Only thing I changed is the store URL and the API password in `config.yml`. Do I need to somehow initialize the theme in the Store? Or should `theme upload` do the deployment from scratch?

**Comment by tanema** [comment]
The theme ID does not stay the same across shops, you will need create a theme on your other shop to upload your files to.

**Comment by hatsumatsu** [comment]
Thanks! But how to create an empty theme without a bootstrpped set of files?

**Comment by tanema** [comment]
To duplicate a theme across shops, you will need to 

- access your online store in the first shop
- click the actions dropdown
- click `Download theme file`
- You will receive an email with a link to download the zip file.
- access the online store for the second shop
- click `upload theme` from the top bar
- select your downloaded zip file.
- click `upload`

I know this doesn't feel like the best operation but because of the restrictions of a theme setup, this is currently the way to do it.
