### ISSUE TITLE
User experience issues with theme.lock and theme download

### ISSUE THREAD

**Issue by tstricklin-atmosol** [Shopify/themekit#456]
Hello all.  I appreciate the changes to themekit 0.7.2 to attempt to reconcile changes on remote files.  However, I worry that these same changes will result in a loss of work for local files.  When one attempts `theme upload` and a remote file has been changed, themekit suggests running `theme download` and merging changes locally...  But if local changes have not been committed to git/VCS, running `theme download` will overwrite those changes.

It would be nice if themekit would facilitate some kind of merge conflict resolution as part of the download, but I suspect this is well outside the scope of what you want themekit to handle.

Instead, perhaps the best approach would be to look for unexpected **local** changes on theme download. If the local file has a different hashsum than what is recorded in theme.lock, a similar error message would occur, prompting the user to either revert the file or use a --force flag.

In any case, I believe the verbiage of the current `theme upload` error message should be changed to warn the user to back up, commit, stash, etc. their local changes before running `theme download`.

### What I expected to happen

Either of three possibilities:

- When I run `theme download` on a file that has unexpected remote changes, it should create a new copy of the file, or a file with merge conflict notation, or otherwise preserve my local changes; **or**
- When I run `theme download` on a file that has unexpected remote changes, themekit should also look for unexepcted _local_ changes and, upon detection, reject the download, requiring a `--force flag`; **and/or**
- When I run `theme upload` and get the warning about unexpected changes on remote, it should warn me that downloading the files will overwrite any local changes to my file.

### What actually happened

My local changes are overwritten by `theme download` with no warning.

### Steps to reproduce

1. Upload a file via `theme upload`
2. In a different local environment, download that file via `theme download`, make changes, and upload via `theme upload`
3. In your original local environment, make a change to that file and attempt to `theme upload`.  You should receive an error message about `Unexpected changes on remote`, including the following verbiage:
    > You can solve this by running theme download and merging the remote changes
    > using your favourite diff tool or if you are certain about what you are doing
    > then use the --force flag
4. Run `theme download` on that file.  Your local changes will be overwritten.

### My Environment

OS (including version): macOS Sierra
Themekit version: 0.7.2 darwin/amd64
Ignore Files(if any): config.yml (.gitignore)

**Comment by tanema** [comment]
Hey @tstricklin-atmosol, thank you for the fully detailed issue request. I thought about this issue over the weekend and I think this is not something we will pursue. 

If I were to implement this I would have to compare the checksum with the current file on disk before writing the new one. A few issues are raised by this.

- If the checksum is different from the file on disk this only means that changes have not been uploaded to shopify and not that they have not been persisted in VCS. This does not prevent changes from being overwritten.
- The checksum may be different just because the developer changed branches in VCS
- Because of the previous problems it would become very common for developers to have to run download with a force flag. It would become just more characters to type and a frustration for developers.
- Themekit is meant to stay VCS agnostic so that any user can use any tool they wish and tailoring themekit to VCS usage breaks this.

The features implemented recently were meant to prevent problems between developers and between developer and client when communication has failed. This project is not meant to re-implement a VCS and at a certain point the developer needs to take responsibility for lost work.

**Comment by tstricklin-atmosol** [comment]
Hi @tanema, thank you.  I think your rationale against adding checking for local file changes is sound.  I would hope, though, that some verbiage be added to the error message or at least somewhere in the documentation.

I agree, a developer should hopefully realize the implications of running `theme download` against local uncommitted code--and to your point, I did `git stash` before attempting--but the current verbiage on the new `theme upload` error message may create a sense of false hope.

Thanks again!

**Comment by tanema** [comment]
> I would hope, though, that some verbiage be added to the error message

Which error message are you talking about in particular. Can you paste it here and explain what you find confusing about it?

**Comment by tstricklin-atmosol** [comment]
```
10:08:44 Unexpected changes made on remote.
Diff:
        Updated Files:
                - assets/******.css local:[Jul 23 1:27AM 2017] remote:[Jul 24 1:27AM 2017]

You can solve this by running theme download and merging the remote changes
using your favourite diff tool or if you are certain about what you are doing
then use the --force flag
```

My concern is that recommending the user to run theme download (and perhaps especially suggesting a merge "using your favourite diff tool") will give the impression to some that `theme download` plays nice with the local files--in other words, hinting at more advanced functionality than actually exists within themekit.

**Comment by tanema** [comment]
Okay thanks I will change that error message to more clear about possibly overwriting local changes.

**Comment by tstricklin-atmosol** [comment]
That sounds great! Thank you.
