### ISSUE TITLE
Theme Watch not notifying --notify=/tmp/somefile

### ISSUE THREAD

**Issue by webberwang** [Shopify/themekit#474]
### What I expected to happen
On watch the /tmp/somefile should be created & updated

### What actually happened
Themekit doesn't update the file

### Steps to reproduce

1. theme download
2. theme watch --notify/tmp/somefile
3. Make changes

### My Environment

OS (including version): 10.12.6
Themekit version: 0.7.5
Ignore Files(if any): none

**Comment by tanema** [comment]
Hey @webberwang I cannot reproduce this. 

Here is what I am doing and maybe we can clarify where the problem is
- `theme watch --notify=/tmp/somefile`
- change `assets/app.js`
- wait for themekit to say `Successfully performed Update on file assets/app.js`
- check that `/tmp/somefile` was created
- change `assets/app.js` again
- check that `/tmp/somefile` timestamp has changed

Do you have the correct permissions to write to `/tmp`?

**Comment by webberwang** [comment]
Shouldn't /tmp directory should be created by theme watch? Or do we need to manually create the directory?

**Comment by tanema** [comment]
The /tmp file is standard in a lot of systems but not all. No theme kit will not make the directory. You need to provide themekit with a valid path.
