### ISSUE TITLE
Having nicer exit codes when something fails

### ISSUE THREAD

**Issue by starstuffharvestingstarlight** [Shopify/themekit#479]
### What I expected to happen

When uploading using `theme upload` and `theme replace`, if one or more files failed (e.g., 422 Unprocessable Entity), exit code indicates failure (`>= 0`).

### What actually happened

Exit code indicates success (`0`)

### Steps to reproduce

1. `theme download`
2. edit theme.liquid and remove a part of the theme (like `{{content_for_layout}}`)
3. `theme upload`
4. `echo $? # returns 0`

### My Environment

OS (including version): `Linux  4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Themekit version: `ThemeKit 0.7.5 linux/amd64`
Ignore Files(if any): 

### Discussion

I've been using `theme` for automated deployment and it's fantastic, but I'd like the build to fail when a template is incorrect. 

Is there a validation command, or is it always done during upload? Say if a template has an error, will the whole upload be rolled back, or does the theme stay in an inconsistent state?

I've been using it wrapped in a script, which works, but isn't ideal:
```bash
#!/bin/bash

ERRFILE=$(mktemp)

$* 2>$ERRFILE

if [ ! -z "`cat $ERRFILE`" ]
then
	echo 'Command failed. Error output:'
	cat $ERRFILE
	rm -f $ERRFILE
	exit 1
else
	rm -f $ERRFILE
	exit 0
fi

```

Maybe a `--validate` command that would attempt but not commit the theme, or just returning an unsuccessful exit code? Happy to have a go at fixing this but my go isn't the best

**Comment by tanema** [comment]
The problem with enforcing an exit code is that when we get an error code from Shopify, this is not a crashing themekit error, it is a Shopify error. I may be able to implement a proper error exist status for these cases but I will have to think about the implications it has on other tools before I do.

As for validation, theme kit is really just a client to Shopify's API. There is no validations, checking before files are uploaded. There is no way currently to check if a file will upload successfully because themekit does not compile the themes and I cannot get the information from the API. This also means unfortunately that I cannot develop a rollback strategy either. I could try and save the file contents of the files that are being overwritten but I have no confidence that I could upload them successfully again while trying to rollback.

**Comment by starstuffharvestingstarlight** [comment]
Yeah that's fair enough, I guess a wrapper script works just as well. 

Here's one in case anyone runs into this thread later on, it does a full 'transaction' based theme replacement and reads environment settings from an `.env` file if it exists.

I think this issue can be closed as well. Thanks!

```bash
#!/bin/bash

error_output_file=$(mktemp)
temp_theme_directory=$(mktemp -d)

cleanup() {
	rm -rf $error_output_file $temp_theme_directory
}

env_theme() {
	if [ -f .env ]
	then
		env $(cat .env | grep -ve '^#.*' | xargs) theme $*
	else
		theme $*
	fi
}

echo "Saving theme backup to $temp_theme_directory"

env_theme download -d $temp_theme_directory

env_theme replace 2>$error_output_file

if [ ! -z "`cat $error_output_file`" ]
then
	echo 'Command failed. Error output:'
	cat $error_output_file

	echo 'Rolling back to previous theme'
	env_theme replace -d $temp_theme_directory

	cleanup

	exit 1
else
	echo 'Theme applied'

	cleanup

	exit 0
fi

```
