### ISSUE TITLE
upload command erase section already defined on the Shopify server

### ISSUE THREAD

**Issue by pdion** [Shopify/themekit#487]
### What I expected to happen

I expected using the _theme upload_ command would preserve the sections already set on the shopify server.

### What actually happened

running _theme upload_ all sections defined on the Shopify server are deleted.

### Steps to reproduce

1. Create some sections.
2. Add those section on the Shopify server.
3. Run _theme upload_

All previously sections set are gone.

### My Environment

OS (including version): Ubuntu 16.x
Themekit version:
Ignore Files(if any):

**Comment by tanema** [comment]
Which themekit version are you using.

**Comment by tanema** [comment]
why are you using themekit instead of `slate deploy`?

**Comment by pdion** [comment]
Because `slate deploy` use `theme replace` instead of `theme upload` - or it is my understanding.

**Comment by tanema** [comment]
yes and why is that bad?

**Comment by pdion** [comment]
if the client add files from the server, all those will be erased when I push. Not very collaborative.

**Comment by tanema** [comment]
Ah I see, slate is still using 0.6.12. Themekit in version 0.7.x has a manifest that protects against these issues. 

As a side note, upload in version 0.6.x will overwrite all the files on the server. So even if your client has added files it doesn't matter because there will no longer be any reference to the file in the files that were overwritten.

**Comment by pdion** [comment]
OK, thank you
