### ISSUE TITLE
Trojan found after the last theme.exe update

### ISSUE THREAD

**Issue by morkoffkin** [Shopify/themekit#541]
### What happened
I updated Themekit to the latest version (with **theme update** command) and Kaspersky Internet Security found a virus in **theme.exe** file: 

Also, here is some info from virustotal.com: https://www.virustotal.com/en/file/bac29a37dd7905411bc022687df61b8a431417348ff12cf3a5f32b63b0f1c025/analysis/1534839190/

### My Environment

OS (including version): Windows 7 (x64)
Themekit version: last version (can't find the number because Kaspersky removed the file)

**Comment by tanema** [comment]
Okay I can guarantee that the file would be safe as long as the checksum passes so this must be a false positive. I will have to figure out how to whitelist the application.

Until then, how did you originally install it? Can you whitelist it yourself?

**Comment by tanema** [comment]
@morkoffkin I have added md5 checksums to the downloads so if you download it directly here https://shopify.github.io/themekit/#manual-installation, you can check to be certain that the binaries have not been tampered with.

**Comment by morkoffkin** [comment]
@tanema ok, thank you!
Now I'm scanning my PC with Kaspersky and another anti-virus software (to make sure that my environment is ok).

**Comment by tanema** [comment]
It seems like there isn't anything I can do about this since a couple viruses have been written in Go and some of the virus scanners match with similar compiled data. Even the go compiler itself seems to have this issue. 

I believe as long as I can provide checksums for making sure that the binaries are safe to download and use they should be good. The update command uses checksums. The homebrew formula uses a checksum, so I think we are pretty safe. Thank you for opening the issue, and having me look at this more closely.

**Comment by morkoffkin** [comment]
@tanema I sent this file to Kaspersky Lab — they confirmed that this is a false positive. It will be fixed in new versions of their database.
