### ISSUE TITLE
Missing old error: Cannot overwrite generated asset

### ISSUE THREAD

**Issue by mtm-sig** [Shopify/themekit#577]
### What happened

theme deploy stalls when trying to upload a generated asset. It tries to deploy the same file over and over.

### What I expected to happen

To get the old error: `Cannot overwrite generated asset`, and an option to ignore the error.

### Steps to reproduce

1. create style.scss and style.css
2. run theme deploy --no-delete
3. themekit can't upload style.css because shopify generated a new style.css

### My Environment

OS (including version): MacOS 10.13.6
Themekit version: 0.8.1
Editor (including version): Atom 1.30.0
Ignore Files(if any):

**Comment by tanema** [comment]
Ah yes this is because if it notices that you are trying to do that, it will assume you renamed it or know what you are doing, so it will try and delete the old file and just create it new. Here is the code for reference. https://github.com/Shopify/themekit/blob/master/src/shopify/theme_client.go#L270-L279

This has been a feature since 0.6.11 I believe. What it should not do though is trying over and over again. I will look into why it hangs.

**Comment by tanema** [comment]
I have merged a fix for this and it will be in the next release.
