### ISSUE TITLE
Add timestamps to all commands

### ISSUE THREAD

**Issue by cameroncowden** [Shopify/themekit#632]
**Is your feature request related to a problem? Please describe.**
Sometimes I return to the terminal and it would be nice to know when commands were run, or finished running. 

**Describe the solution you'd like**
It currently does it for `theme watch`, but it would be nice if it added timestamps to the beginning of all new lines. E.g. timestamp at the beginning and end of `theme download`.

**Describe alternatives you've considered**
`date`
`theme download -e=production && date` would work as long as there were no errors I think..

**Additional context**
For freelancers and others tracking time, sometimes it's nice to have LOTS of timestamps to keep up with when you were doing what.

**Comment by tanema** [comment]
I don't think I should add extra output like this as default. The timestamps were added to watch because it is common to change the same file over and over then check if it uploaded so it was good for making sure the most recent change was uploaded. I don't think this sort of information applies here. 

I could add a flag to add the time output to the command but it sounds like you track your activity on your command line and you would probably benefit from just adding the time to your shell prompt.

**Comment by cameroncowden** [comment]
Oh, I didn't know that was possible! That should work just fine. I found a link with instructions [here](https://askubuntu.com/questions/193416/adding-timestamps-to-terminal-prompts). Thanks!
