### ISSUE TITLE
McAfee is saying Windows 32 & 64 bit versions of Theme Kit has a virus

### ISSUE THREAD

**Issue by jahodson3** [Shopify/themekit#668]
When I try to download the Windows 32 or 64 bit version of Shopify Theme Kit at https://shopify.github.io/themekit/#installation, McAfee is trying to block the download stating it contains a virus.  Is this normal or is the distribution infected?

**Comment by tanema** [comment]
No, this has happened in the past. If you are using chocolatey to install the binary is checked with the checksum. If you are just downloading the binary, please check the binary with the provided checksums if you are worried. 

This happens from time to time because most virus scanners look for patterns in binaries and since themekit is written in go, and some viruses are written in go, virus scanners can often find similar patterns. I will look into getting our binaries whitelisted again so this does not come up again.

**Comment by tanema** [comment]
Okay I have submitted a ticket about this to mcafee, and honestly this will probably happen again in the future releases. If you are on windows I recommend using chocolatey. Their services reviews files and checks the files with a checksum to make sure it did not fall victim to a MIM attack.
