### ISSUE TITLE
Disable "theme publish"

### ISSUE THREAD

**Issue by iant2** [Shopify/themekit#683]
**Is your feature request related to a problem? Please describe.**
I wish to disable a developer's ability to publish a theme. I have a private app pointing to a theme that I have designated "Development" and I do not want to run the risk of having that theme published live 

**Describe the solution you'd like**
A way to disable theme publish permissions for a specific private app, a way to protect the current live theme from being unpublished, or a way to white list "development" themes from being published

**Describe alternatives you've considered**
Returning to an older version of theme kit

**Comment by tanema** [comment]
Hi @iant2, this is not a themekit problem but rather a permissions problem. If you really want to pursue this I would suggest making a request through our support. 

The reason that it is not a themekit problem is that the API will still just be accessible so if a developer was persistent, they could just make a simple HTTP request to the API. This is because if they have access to modify theme files, then they have access to modify the theme's published attribute. 

Have you had instances where someone has done this either intentionally or unintentionally?

**Comment by iant2** [comment]
@tanema no I haven't, I was just establishing a development environment, with dev, stage, and prod themes, and I just noticed that with theme publish any developer could take a test theme live at any moment. Is there a best practice for establishing a setup as i describe?

Thank you for suggesting the permissions feature request.

**Comment by tanema** [comment]
The publish action was highly requested by most theme developers. It is a longer command, so hard to mistype and I haven't heard of missteps using it. Normally I suggest that you set your production theme to readonly in your config however that will not prevent the publishing of another theme. Also, it is a quick action so if somehow it happened, it could be undone very quickly as well.

**Comment by iant2** [comment]
thanks for the feedback, do you know the right repo to submit a feature request for publish permissions?

**Comment by tanema** [comment]
You need to contact support. This is a core part of how Shopify's permission system works. I am not sure they will implement it but these sort of requests get put into a database meant to help us make our platform better

**Comment by tanema** [comment]
Since this is not an issue with themekit I am going to close this issue. If support is added to shopify to allow themekit to leverage it then I will address this again
