### ISSUE TITLE
Permissions after update

### ISSUE THREAD

**Issue by paulmann2021** [Shopify/themekit#701]
I installed themekit for the first time using the windows manual instructions. My first pull of a dev theme told me themekit needed an update. I had to run the update in windows powershell as an admin. 

After the update my c:/Program Files/Theme Kit/ was empty ( my previously copied themekit.exe file was gone ) 

I can't retrace my steps as now copying themekit.exe into the folder isn't allowed without administrator permission ( I am an administrator )

**Comment by paulmann2021** [comment]
******************************************UPDATE*********************************
AVG had deleted the theme.exe file because it was infected with IDP.ALEXA.52

?!?!?!?!?!?!?

**Comment by paulmann2021** [comment]
*************************UPDATE V2
renaming Theme Kit folder to ThemeKit allows me to copy the theme.exe file in - try to run update again, downloads theme.exe.new but AVG kicks in again telling me its infected with  IDP.Generic

**Comment by tanema** [comment]
Have you tried installing using chocolatey? That might solve some of your issues. Sometimes virus software thinks that themekit is a virus because it is a binary compiled with Go. That means the binary can have some similar patterns within it that match real viruses. If you are worried, please use the checksums to confirm that they have not been compromised.
