### ISSUE TITLE
How to create layout/password.liquid file 

### ISSUE THREAD

**Issue by Freelancer740** [Shopify/themekit#703]
Hello,

I have just created a new theme started customizations when I am trying to create a layout file for the password page then I'm not getting any option please let me know how can I do that.

**Comment by liamgriffin** [comment]
Hi there @Freelancer740 

We have a full guide on how to work with the password layout file [on our Shopify Partners blog](https://www.shopify.ie/partners/blog/customize-shopify-password-pages-with-the-password-liquid-template). 

This should explain how to create the `password.liquid` file and what needs to be contained within it, so that it's functional.
