### ISSUE TITLE
Themekit v1.0.3 Could not find command "new".

### ISSUE THREAD

**Issue by alibellahrach** [Shopify/themekit#711]
Hi there,
Im on OSX Catalina.
Just installed Themekit using brew 
Themekit version is v1.0.3 
When I try to create a new project I get:
Could not find command "new".

Can some one help with this please? 

Cheers

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Catalina
- Themekit version [e.g. v0.7.5]: v1.0.3

**Comment by tanema** [comment]
- How did you install
- What is the exact command that you are running?

**Comment by alibellahrach** [comment]
> * How did you install
> * What is the exact command that you are running?

Hi Tanema,
Thank you for looking into this!

I installed it using brew, i run:
```
brew tap shopify/shopify
brew install themekit
```
Following the install instruction on https://shopify.github.io/themekit/

Cheers

**Comment by alibellahrach** [comment]
Hi @tanema,

any update on this one?

Cheers

**Comment by tanema** [comment]
What is the output of `theme version` because it does not seem like you have the correct version installed if you cannot run `theme new` 

If you have the incorrect version installed you can remove it by running `rm $(which theme)` continue to do that until you no longer have any instance of it installed and then re-install it.

**Comment by alibellahrach** [comment]
Thanks! 
that did the trick! I had some old install still there.
