### ISSUE TITLE
[UX] Indicating skipped files for upload and deploy

### ISSUE THREAD

**Issue by andyw8** [Shopify/themekit#727]
With the upcoming support for checksums, we need a way to indicate if an asset is skipped when running the `deploy` or `download` commands in verbose mode.

This means instead of:

`[development] Updated templates/cart.liquid`

we might say:

`[development] Skipped templates/cart.liquid`

We'll need to decide on both text and colour.

(Another possible approach might be skip the line entirely, and then just give a count afterwards, e.g.:
`13 files were skipped because they are already up to date`.)

@Nupur-Mukherjee, @attaboy, @tanema

**Comment by vfonic** [comment]
> [development] Skipped templates/cart.liquid

This doesn't say the most important part of skipping this file: _why_

I'd just write:

`[development] Identical templates/cart.liquid`
(to keep the `[env] [status] [file]` order)


Here, I'd maybe add a comma-separated list of files, just so user (me) can go back to terminal and find these files being skipped for a reason:
`13 files were skipped because they are already up to date.`

Just my $0.02. Thanks!

**Comment by tanema** [comment]
The newest version has been shipped with the output of how many files were skipped
