### ISSUE TITLE
Request Rate Limiting not working for theme remove

### ISSUE THREAD

**Issue by cameroncowden** [Shopify/themekit#751]
**Bug description**
Sometimes it makes sense to store images as assets. I have ~300 images to remove. Naming format is design_left_a_blue.png, design_right_g_red.png etc. Running `theme remove -e=staging assets/design_*` throws a bunch of "Exceeded 2 calls per second for api client. Reduce request rates to resume uninterrupted service." errors.

**Expected behavior**
It should slowly work it's way though all the files, just like it does for `theme deploy -e=staging assets/design_*`.

**Environment (please complete the following information):**
 - MacOS 10.15.4
 - ThemeKit 1.0.3 darwin/amd64
 - happening in bash
 - Ignore: none

**Additional context**
Not a huge issue, running the command a few times eventually gets them all.

**Comment by tanema** [comment]
This may be because you are running more than one themekit on a single private app because all asset calls (CRUD) are run through the same client based on the same throttling. So the throttling would take effect. It is common the people don't realize that many themekit instances are running though. 

I am hoping to ship #747 in the next release coming out soon which will use more intelligent throttling that will limit across multiple instances so this should not happen in the future.

**Comment by tanema** [comment]
This should no longer be an issue in the newest version
