### ISSUE TITLE
Feature req: Add back "live" option for theme_id

### ISSUE THREAD

**Issue by vfonic** [Shopify/themekit#769]
**Is your feature request related to a problem? Please describe.**

I've got a client who knows some basic HTML and sometimes he makes some changes through Shopify admin ("Edit code"). He always duplicates the theme before doing so in order to be able to quickly publish the backup/duplicate theme if he messes things up.
Now this process of publishing backup/duplicate theme obviously changes the theme_id of live theme.
I really liked the feature of being able to write `theme_id: 'live'` (actually I would just comment out this line in config and it would use live theme when no `theme_id` was selected.

Today I noticed these changes and I'm hesitant to upgrade my themekit version:
https://github.com/Shopify/themekit/commit/9079a7a651e46d2a435ef68ac0ba7f18ce7eb92f#diff-2db8f261e1d717489d4af55327c6e926R54-R57

I'm stuck on ThemeKit 1.0.3 darwin/amd64 right now.

How can I have theme kit interact with live theme without me having to know the live theme theme_id?

Thanks!

**Comment by tanema** [comment]
We wanted to move away from anything that makes it easier to interact with the live theme because a lot of people found them dangerous. You could use `theme get --list` to list the themes and both the theme IDs are in there as well as the live theme is indicated in that list as well.

This is an example output from my own store.
```bash
➜  can-i-buy-a-feeling.myshopify.com theme get --list
Available theme versions:
  [80819355670][live] mynewtheme
  [81037754390] mynewtheme
  [105994886] Brooklyn
```

**Comment by vfonic** [comment]
Wouldn't you agree that that's, at least for my use-case, worse experience than what I have right now?

This is a dealbreaker for me actually and I'll have to postpone upgrading the themekit for as long as possible.

I think keeping "live" wouldn't make it "dangerous". I mean, if it did, perhaps it's dangerous for that developer to have any access to the theme. It literally says it's live theme.

I like the simplicity and putting some guards in place, but in this case, I see this more of a move in "this is for your own good" direction than a truly enhancing DX feature.

**Comment by tanema** [comment]
I understand how important this is to you but there are several things that are a bit to easy to do that could take out a shop and cause long periods of downtime. For some merchants this has been disastrous. There are other issues like the ability to overwrite the settings so easily. This all still points back to the live theme because overwriting the settings by accident can cause extreme downtime as well but just annoyance on a development theme.
Ultimately DX includes both what you are enabling developers to do as well as what problems you are helping developers avoid. If you end up causing an outage after explicitly querying and using the theme ID and the `--allow-live` flag, then this can no longer be the fault of the tool.

**Comment by vfonic** [comment]
Man, making any theme changes by uploading and overwriting a file by file
is...do I even have to comment on why this is bad in so many ways in 2020?

Fixing the problem at its core would be much better way forward.

I think the state of theme development tools is a total disaster. First you
deprecate slate, now you're cutting down on features. Well, thanks for
providing an alternative configuration option I can use to go around...

Feel free to close this issue. It's clear that we don't agree. Have a good
day.
