### ISSUE TITLE
Live Theme Backups using themeid: live

### ISSUE THREAD

**Issue by Powellze** [Shopify/themekit#785]
**Is your feature request related to a problem? Please describe.**
In the latest version of themekit the 'live' theme id is no longer available, we use this for getting live backups for deployments.

**Describe the solution you'd like**
Allow a theme id of 'live' to be set which targets the live theme for making daily backups.

**Describe alternatives you've considered**
Although it's possible to add a theme_id to a continuous deployment process, using the "live" theme id allows us to target the live theme and download backups.

**Comment by curiouscrusher** [comment]
I definitely second this. The ability to download the currently published theme by using `theme_id: "live"` was a huge benefit! Taking it out of both `deploy` and `download` seems like a bit of an oversight since _downloading_ the current live theme shares essentially none of the consequences as unintentionally overwriting a live theme via `theme deploy ...`. 

Would love to see this functionality added back to the `theme download ...` command as it was almost a daily command for myself and many others.

**Comment by dgpokl** [comment]
Thirding this. The command: 
```
theme download --themeid live --dir dist config/settings_data.json
```
was what we use(d) in our CI script to grab the production settings data just before uploading a new theme to replace it. This ensures that site settings, which are extensive and precious, are always preserved. Now we need to run:
```
LIVE_THEME_ID=$(theme get --list  | fgrep '][live]' | tr '[]' '  '  | awk '{print $1;}' | tr -d '\n')
theme download --themeid $LIVE_THEME_ID --dir dist config/settings_data.json
```
Fun mostly unrelated fact, `theme get --list` takes 22 seconds to execute for me. wtf? This means that adapting to this change adds 22 seconds to every build for us.

**Comment by tanema** [comment]
Since we will not be merging anything around Black Friday/Cyber Monday, I have created a prerelease with the fixes for this issue included in it. You can install the prerelease by running theme update --version=v1.1.3-pre, please share any feedback that you have on this.

This pre-release adds a `--live` flag to `get`, `download` and `configure` so that you may automatically set your confiuration to fetch the live theme without specifying a themeID
