### ISSUE TITLE
Using Theme Kit as a team member

### ISSUE THREAD

**Issue by mizujin** [Shopify/themekit#821]
**Is your feature request related to a problem? Please describe.**
Hello! We have been using Theme  Kit for quite a while and we love it. It works perfectly for our needs when developers are alone on a single projects. For bigger stores, we sometime needed 2-3 developers to join force on the same project. We would initiate a git repo, each working on separate branches & Shopify themes. We would then proceed to a manual files merge in the end.

**Describe the solution you'd like**
Could it be possible for multiple devs to work a single theme concurrently ? If not, is there any practical way to do theme development as a team on Shopify ?

**Describe alternatives you've considered**
One proposed temporary solution was to use Visual Studio Code Live Share feature to work simultaneously. We would have liked a more official way to do so, because this still can be error prone.

Thank you very much for your help and feedbacks !

**Comment by andyw8** [comment]
Hi @mizujin 

We aim to keep Theme Kit unopinionated about workflow, so that teams can build their own process on top of it, suited to their specific needs.

Using git is a popular approach. You can certainly have multiple devs working on a theme concurrently. Where you might run into challenges is when different people have worked on the same file independently, and you needs to bring the changes back into a single master branch. Conflicts can be difficult to address, but there are some practices to reduce that pain:

- Avoid long running branches
- Frequently update your branch with the latest changes in the master branch
- If making large changes, co-ordinate with other developers beforehand to minimize disruption

VS Code Live Share would be useful if you are all working together on the same task, but I don't think it would be effective if you're working on different things, it serves a different purpose.
