### ISSUE TITLE
Custom checkout options are getting reset after a deployment

### ISSUE THREAD

**Issue by lamalamaMark** [Shopify/themekit#876]
**Describe the bug**
Custom checkout options are getting reset after a deployment. For example, a custom logo and custom accent colors is set back to the default options.

**To Reproduce**
1. Customize the checkout via Settings > Checkout in the Shopify admin
2. run command 'theme deploy --env=production --allow-live
3. Checkout custom checkout settings and see they are all set back to default

**Expected behavior**
We expect that custom settings are kept in tact.

**Environment**
- OS , macOS Catalina
- Themekit version 1.1.4
 - Editor Sublime
 - ignore_files:
    - node_modules/
    - parts/
    - components/
    - base/

**Comment by andyw8** [comment]
Hi @lamalamaMark

This is likely because some entries in your local config in `config/settings_data.json` are overwriting settings made in Admin.
There are two ways around this:
* You can choose to add this file to the `ignore_files` in the Theme Kit `config.yml`.
* You can download the settings before deploying with `theme download config/settings_data.json`.

**Comment by lamalamaMark** [comment]
Awesome, definitely was causing the situation.

**Comment by andyw8** [comment]
Ok, good to hear. I've opened #877 to see we can make this clearer.
