### ISSUE TITLE
theme replace only deleting files

### ISSUE THREAD

**Issue by t-kelly** [Shopify/themekit#97]
![image](https://cloud.githubusercontent.com/assets/4837696/9966707/62d0ebe4-5e0c-11e5-8c24-34790760cfff.png)

**Comment by csaunders** [comment]
Are you using v0.3.0?

**Comment by cshold** [comment]
on 0.3.1 `theme replace` hangs and doesn't do anything at all for me

**Comment by cshold** [comment]
Can confirm that `theme replace` is only deleting files. 
![screen shot 2015-09-22 at 10 55 19 am](https://cloud.githubusercontent.com/assets/1730309/10021942/713450f4-6118-11e5-8b23-a36e924f06b0.png)

**Comment by cshold** [comment]
@t-kelly let us know if you see this issue still (if themekit got working for you again that is). I can't recreate it again.

**Comment by t-kelly** [comment]
@cshold Yep - still only removes files. http://tk-demo-test.myshopify.com/

**Comment by t-kelly** [comment]
Watch still does not work either.

**Comment by csaunders** [comment]
There is something weird going on here as it seems to only be happening to some people. From what I have gathered the application is running on the host, so it should be working fine.

Could there be something broken/messed up with FS events not getting fired correctly? We will need to figure out more details because it's extremely hard to replicate.

Looking at the output from mitmproxy, there appears to be a problem with how we are collecting local files and doing the merge. We might want to include more details (maybe via a verbose mode?) in the logs to assist with debugging.

**Comment by stewartknapman** [comment]
I'm assuming this is the same or similar issue that I'm having. `theme watch` jumps between remove and update: https://monosnap.com/file/vbPbhmWCYQchV6hklYPHjH6SC9CT12

version: Theme Kit v0.3.6

**Comment by bhekuwenza** [comment]
Have this issue too. After troubleshooting with my colleagues, it seems to only do this when using 'textmate' as the editor on OSX. Brackets and TextEdit, seem to work fine. I can't speak for other editors like Sublime etc. We just pinned the issue to Textmate's saving. Which is strange because scss files are fine when saved and upload succesfully.
