### ISSUE TITLE
Theme watch has file length limit?

### ISSUE THREAD

**Issue by cshold** [Shopify/themekit#99]
Uploading [this very long css file](https://github.com/Shopify/shopify-themes/blob/master/Lookbook/assets/style.scss.liquid) from Lookbook via `theme upload assets/style.css.liquid` works as expected. When uploading via `theme watch`, it seems to cut off at 4394 lines.

Can replicate on https://carson-dev-shop-2.myshopify.com/ (PM me for themekit credentials).

**Comment by ilikeorangutans** [comment]
@cshold Tried to replicate the issue but was unable to; added the file in question to my theme, started watch and modified it. Compared md5 sums from file from before and after and they seem ok. 

Can you still replicate this with the latest version?

**Comment by cshold** [comment]
This was fixed in either v3.0.0 or v3.0.1 I believe (can't find the PR, but remember not being annoyed by the issue anymore). Haven't had the issue since so consider it resolved.

**Comment by cshold** [comment]
Found it - https://github.com/Shopify/themekit/pull/112

**Comment by AlfalfaAnne** [comment]
I'm having the same issue with long files (both JS and CSS). 

Details:
- no errors from Terminal and the "Successfully performed Update operation for file" is returned
- long file is cut off at random (usually 4000 line mark)
-  if I stop the current `theme watch` and rerun, it generally works, but only the first time
- only happens with extremely long files and if I shorten them, it's all good
- never had this issue with the theme gem - it's only come up since I swapped to Theme Kit

Running:
Sierra 10.12
Theme Kit v0.4.3
